name: Docker-CI

on:
  push:
    branches:
      - main
      - actions-update
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:  
  build:
    # Install/build maven dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up archived Oracle JDK 17.0.3.1
      uses: oracle-actions/setup-java@v1
      with:
        website: oracle.com
        release: 17
        version: 17.0.3.1
    - name: Maven build
      run: |
       echo "maven build - Clean install"
       mvn clean install -Dmaven.test.skip=true
       mkdir -p target/dependency && (cd target/dependency; jar -xf ../elrrservices-0.0.1-SNAPSHOT.jar)
    - name: Docker login
      env:
       DOCKER_USER: ${{ secrets.DOCKER_USER }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
       echo "Authenticate to Docker"
       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Docker build
      run: |
       echo "Start docker build"
       #docker build . -t openlxp/elrr-services
       docker build --build-arg JAR_FILE="./target/elrrservices-0.0.1-SNAPSHOT.jar" --file Dockerfile -t openlxp/elrr-services .
    - name: Push Image
      run: |
       echo "Push new image to the Dockerhub repository"
       docker push openlxp/elrr-services
