apiVersion: v1
kind: Service
metadata:
  name: elrrservices-k8s-svc
spec:
  selector:
    app: elrrservices-k8s
    type: NodePort
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30037